# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d1f5c854b1af0b5ace7dba6cbaa48a9752044e81699afc04c0a23ce153d648eefa6772621fc6db4e594f3cde6f82a379e3dee0b6a50297aaba9c63c3792f76a

test:
  secret_key_base: 6a4f69f8db721efc77663bd29ca04fd10aadb1bd38a77c115d4590b072a95838350f200a588bb3bc250e6f6b6f8b825bdefddf14c92b51724c1213b48ac8d9c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
